########################################################################
# Copyright (c) 1988-2018 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 10/19/2018
#
# generic Gcc Makefile for framework Library libframework
########################################################################


#
# target
#
libframework_LIBTARGET = libframework.${LIBEXT}

########################################################################

#
# user c++ flags
#
libframework_USRCXXFLAGS += \
${framework_USRCXXFLAGS} \

#
# user defines
#
libframework_USRDEFINES += \
${framework_USRDEFINES} \

#
# user includes
#
libframework_USRINCLUDES += \
${framework_USRINCLUDES} \

#
# user libdirs
#
libframework_USRLIBDIRS += \
${framework_USRLIBDIRS} \

########################################################################

#
# Library .c sources
#
#libframework_LIB_C_SOURCES += \
#${FRAMEWORK_SRC}/framework/base/Base.c \

#
# Library .cc sources
#
#libframework_LIB_CC_SOURCES += \
#${FRAMEWORK_SRC}/framework/base/Base.cc \

#
# Library .cxx sources
#
#libframework_LIB_CXX_SOURCES += \
#${FRAMEWORK_SRC}/framework/base/Base.cxx \

#
# Library .cpp sources
#
#libframework_LIB_CPP_SOURCES += \
#${FRAMEWORK_SRC}/framework/base/Base.cpp \

#
# Library .m sources
#
#libframework_LIB_M_SOURCES += \
#${FRAMEWORK_SRC}/framework/base/Base.m \

#
# Library .mm sources
#
#libframework_LIB_MM_SOURCES += \
#${FRAMEWORK_SRC}/framework/base/Base.mm \


########################################################################




